version: "3.7"

services:
  database:
    image: postgres
    container_name: database_finapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=finapi
      - POSTGRES_DB=finapi
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data/
  app:
    build: .
    container_name: finapi
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
